config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "languages#index"
  get "/:code" => "languages#show", as: :language
  get "/:code/legals" => "legals#index", as: :legals
  get "/:code/wiki/:title" => "pages#show", as: :page, constraints: { title: /.+/ }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/google_search_result.rb
# frozen_string_literal: true

require 'net/http'

class GoogleSearchResult
  class SearchError < StandardError; end

  BASE_URL = "https://www.googleapis.com/customsearch/v1"

  def initialize(
    query:,
    key: ENV["GOOGLE_SEARCH_KEY"],
    cx: ENV["GOOGLE_SEARCH_ENGINE"],
    lang: :en
  )
    @query = query
    @key = key
    @cx = cx
    @lang = lang
  end

  def urls(limit: 4)
    response = Net::HTTP.get_response(endpoint)
    unless response.is_a?(Net::HTTPSuccess)
      raise SearchError
    end

    result = JSON.parse(response.body)
    result = result["items"].map { _1["link"] }
    result = result.filter do |r|
      uri = URI.parse(r)
      uri.scheme == "https"
    end
    result = result[..limit]
  end

  private def endpoint
    uri = URI(BASE_URL)
    uri.query = params
    uri
  end

  private def params
    URI.encode_www_form(
      [
        [ "q", @query ],
        [ "key", @key ],
        [ "cx", @cx ],
        [ "lr", "lang_#{@lang}" ]
      ]
    )
  end
end

app/models/google_search_url.rb
class GoogleSearchUrl
  BASE_URL = "https://www.googleapis.com/customsearch/v1"

  def initialize(
    query:,
    key: ENV["GOOGLE_SEARCH_KEY"],
    cx: ENV["GOOGLE_SEARCH_ENGINE"]
  )
    @query = query
    @key = key
    @cx = cx
  end

  def url
    uri = URI(BASE_URL)
    uri.query = query
    uri
  end

  private def query
    URI.encode_www_form(
      [
        [ "q", CGI.escape(@query) ],
        [ "key", @key ],
        [ "cx", @cx ]
      ]
    )
  end
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :pages, dependent: :destroy
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :language
  has_many :references, dependent: :destroy

  def prompt
    <<~MARKDOWN
      You are tasked with creating a Wiki-like summary of information from multiple webpages. The content from these webpages has been combined and will be provided to you. Your goal is to summarize and format this information in a coherent, Wiki-style article.

      Here is the combined content from multiple webpages:

      <webpage_content>
      #{references.map(&:body)}
      </webpage_content>

      Your task is to create a Wiki-like article based on the following topic:

      <topic>#{title}</topic>

      Follow these guidelines to structure your Wiki-like article:

      1. Start with a brief introduction of the topic.
      2. Organize the information into logical sections with appropriate headings.
      3. Include any relevant historical information, cultural significance, or interesting facts.
      4. If there are conflicting pieces of information from different sources, present the most commonly agreed-upon facts or note the discrepancies.
      5. Use a neutral, informative tone throughout the article.
      6. If specific locations or establishments are mentioned, you may include them in a separate section.
      7. Generate long long contents

      Do not include any citations or references to specific websites in your output. Present the information as if it's general knowledge in a Wiki format.

      <language>#{language.code}</language>
      <format>Markdown</format>

      Please provide your Wiki-like article within <wiki_article> tags. Begin your response immediately with the opening tag, followed by your formatted article, and end with the closing tag.
    MARKDOWN
  end
end

app/models/page_reference_search.rb
class PageReferenceSearch
  BASE_URL = "https://www.googleapis.com/customsearch/v1"

  def initialize(
    page:,
    key: ENV["GOOGLE_SEARCH_KEY"],
    cx: ENV["GOOGLE_SEARCH_ENGINE"]
  )
    @page = page
    @key = key
    @cx = cx
  end

  def url
    uri = URI(BASE_URL)
    uri.query = query
    uri
  end

  private def query
    URI.encode_www_form(
      [
        [ "q", CGI.escape(@page.title) ],
        [ "key", @key ],
        [ "cx", @engine ]
      ]
    )
  end
end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :page

  def self.from_html(html_content:, url:)
    doc = Nokogiri::HTML(html_content)
    doc.search("script, style, noscript").remove
    body = doc.text.strip
    body = body.gsub(/\s+/, " ")
    body = body.gsub(/\n\s*\n/, "\n")
    title = doc.at("title")&.text
    uri = URI.parse(url)
    base_url = "#{uri.scheme}://#{uri.host}"
    icon = doc.at('[rel="icon"]')
    image_url = icon ? icon["href"].match("http") ? icon["href"] : "#{base_url}#{icon["href"]}" : ""
    new(title:, body:, url:, base_url:, image_url:)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_locale

  helper_method :language, :language_codes

  private def language
    @language ||= Language.find_by(code: params[:code])
  end

  private def language_codes
    @language_codes ||= Language.pluck(:code)
  end

  private def set_locale
    I18n.locale = language.code
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_locale, except: :index

  def index
    if preferred_language.in?(language_codes)
      redirect_to "/#{preferred_language}"
    else
      redirect_to "/en"
    end
  end

  def show
  end

  private def preferred_language
    request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/legals_controller.rb
class LegalsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.create_or_find_by(title: params[:title], language: language)
    if @page.body
      return
    end
    SearchReferencesJob.perform_later(page_id: @page.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/legals_helper.rb
module LegalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/languages/show.html.erb
<div class="h-[70vh] flex flex-col items-center justify-center">
  <h1 class="text-center font-bold text-3xl flex gap-2 items-center justify-center mb-3">
    <img src="/icon.png" class="w-8 h-8" />
    <%= t("dynawiki") %>
  </h1>

  <form
    data-controller="search"
    data-action="submit->search#submit"
    data-search-locale-value="<%= language.code %>"
    class="py-4 w-full flex justify-center"
  >
    <input type="search" data-search-target="field" class="border border-gray-50 shadow focus:ring-0 focus:outline-none focus:border-gray-50 rounded-lg w-full max-w-[400px] mx-auto" placeholder="<%= t("search") %>">
  </form>

  <footer class="flex justify-center mt-3 text-sm gap-x-2">
    <%= render LanguageComponent.with_collection(
      language_codes,
      current: language.code,
      spacer_component: LanguageSpacerComponent.new
    ) %>
    <div>/</div>
    <a href="<%= legals_path(code: language.code) %>" class="hover:text-gray-400 transition"><%= t("legal") %></a>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dynawiki" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-50 text-gray-800">
    <main class="p-5 max-w-4xl mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/legals/_en.html.erb
<div class="prose mx-auto">
<%= sanitize(
  Commonmarker.to_html(
    <<~MARKDOWN
    ### Privacy Policy

    #### 1. Introduction
    Dynawiki ("the Service") respects users' privacy and strives to protect personal information. This Privacy Policy explains our policies regarding the collection, use, and protection of information on the Service.

    #### 2. Collection of Personal Information
    The Service does not require user registration and does not collect personally identifiable information ("Personal Information"). Users can use the Service anonymously.

    #### 3. Use of Cookies
    The Service uses cookies to enhance the user experience. Cookies are small data files stored in the user's browser, used to optimize the Service's functionality. Users can manage cookie usage through their browser settings.

    #### 4. Data Sharing
    The Service does not share users' Personal Information with third parties, except as required by law or to protect the Service's rights.

    #### 5. Security
    The Service takes appropriate technical and organizational measures to ensure the security of user information. However, complete security of information transmitted over the internet cannot be guaranteed.

    #### 6. Changes
    This Privacy Policy may be amended as necessary. Changes will be notified on the Service. Users are encouraged to review this Policy regularly.

    #### 7. Contact
    For inquiries regarding this Privacy Policy, please contact the Service's support team.

    ---

    ### Terms of Use

    #### 1. Introduction
    These Terms of Use ("Terms") set forth the conditions for using Dynawiki ("the Service"), operated by [Moeki Kawakami](https://moeki.org). Users agree to these Terms when using the Service.

    #### 2. Provision of Services
    The Service provides infinitely generated Wiki pages. Users can freely browse and utilize the content.

    #### 3. User Responsibilities
    Users shall not engage in the following activities while using the Service:
    - Violating laws or public order and morals
    - Infringing on others' rights
    - Unauthorized access, virus distribution, or other malicious activities

    #### 4. File Uploads
    Users can utilize the file upload feature, but uploaded files are temporarily stored and deleted at the end of the session. Uploading inappropriate files is prohibited.

    #### 5. Intellectual Property Rights
    The intellectual property rights of the content posted on the Service belong to the Service or legitimate right holders. Users may not reproduce, republish, or modify content without permission.

    #### 6. Disclaimer
    The Service does not guarantee the accuracy or completeness of the provided information. The Service is not liable for any damages arising from the use of the Service.

    #### 7. Changes to Terms
    These Terms may be amended as necessary. Changes will be notified on the Service. Continued use of the Service after changes implies acceptance of the revised Terms.

    #### 8. Contact
    For inquiries regarding these Terms, please contact [hi@moeki.org](mailto:hi@moeki.org).
    MARKDOWN
  )
) %>
</div>
</div>

app/views/legals/_ja.html.erb
<div class="prose mx-auto">
<%= sanitize(
  Commonmarker.to_html(
    <<~MARKDOWN
    ### プライバシーポリシー

    #### 1. はじめに
    Dynawiki（以下「当サービス」）は、ユーザーのプライバシーを尊重し、個人情報の保護に努めています。本プライバシーポリシーは、当サービスにおける情報の収集、利用、および保護に関する方針を説明します。

    #### 2. 個人情報の収集
    当サービスでは、ユーザー登録は不要であり、個人を特定する情報（以下「個人情報」）の収集は行いません。ユーザーは匿名のまま、当サービスを利用できます。

    #### 3. クッキーの使用
    当サービスは、クッキーを使用してユーザーエクスペリエンスを向上させます。クッキーは、ユーザーのブラウザに保存される小さなデータファイルであり、当サービスの機能を最適化するために利用されます。クッキーの使用に関しては、ユーザーのブラウザ設定で管理することができます。

    #### 4. データの共有
    当サービスは、ユーザーの個人情報を第三者と共有することはありません。ただし、法律に基づく要求がある場合や、当サービスの権利を保護するために必要な場合を除きます。

    #### 5. セキュリティ
    当サービスは、ユーザー情報のセキュリティを確保するために適切な技術的および組織的な措置を講じています。ただし、インターネットを通じた情報伝達の完全な安全性を保証することはできません。

    #### 6. 変更
    本プライバシーポリシーは、必要に応じて変更されることがあります。変更があった場合は、当サービス上で通知されます。ユーザーは定期的に本ポリシーを確認することをお勧めします。

    #### 7. お問い合わせ
    本プライバシーポリシーに関するお問い合わせは、当サービスのサポートチームまでご連絡ください。

    ---

    ### 利用規約

    #### 1. はじめに
    本利用規約（以下「本規約」）は、運営者である [Moeki Kawakami](https://moeki.org) が Dynawiki（以下「当サービス」）の利用に関する条件を定めるものです。ユーザーは、本規約に同意した上で当サービスを利用するものとします。

    #### 2. サービスの提供
    当サービスは、無限に生成されるWikiページを提供します。ユーザーは、自由にページを閲覧し、内容を利用することができます。

    #### 3. ユーザーの責任
    ユーザーは、当サービスを利用する際に以下の行為を行わないものとします。
    - 法令または公序良俗に違反する行為
    - 他者の権利を侵害する行為
    - 不正アクセス、ウイルスの配布、その他の悪意のある行為

    #### 4. 知的財産権
    当サービスに掲載されるコンテンツの知的財産権は、当サービスまたは適法な権利者に帰属します。ユーザーは、コンテンツを無断で複製、転載、改変することはできません。

    #### 5. 免責事項
    当サービスは、提供する情報の正確性や完全性を保証するものではありません。また、当サービスの利用に関連して生じるいかなる損害についても責任を負いません。

    #### 6. 規約の変更
    本規約は、必要に応じて変更されることがあります。変更があった場合は、当サービス上で通知されます。ユーザーは、変更後も引き続き当サービスを利用することによって、変更後の規約に同意したものとみなされます。

    #### 7. お問い合わせ
    本規約に関するお問い合わせは、 [hi@moeki.org](mailto:hi@moeki.org) までご連絡ください。
    MARKDOWN
  )
) %>
</div>

app/views/legals/index.html.erb
<%= render "legals/#{language.code}" %>

app/views/pages/_body.html.erb
<%= Commonmarker.to_html(body.gsub(/<\/?wiki_article>/, "") || "").html_safe %>

app/views/pages/_generating.html.erb
<%= t("generating") %>

app/views/pages/_loading.html.erb
<%= t("loading") %>

app/views/pages/show.html.erb
<%= content_for(:title) do %>
  <%= "#{@page.title} - Dynawiki" %>
<% end %>

<header class="sm:flex mb-4 block items-center">
  <a href="<%= language_path(code: language.code) %>" class="flex gap-2 items-center font-bold mb-2 sm:mb-0">
    <img src="/icon.png" class="w-6 h-6" />
  </a>
  <form
    data-controller="search"
    data-action="submit->search#submit"
    data-search-locale-value="<%= language.code %>"
    class="w-full flex justify-center"
    data-turbo="false"
  >
    <input type="search" value="<%= @page.title %>" data-search-target="field" class="border border-gray-50 shadow focus:ring-0 focus:outline-none focus:border-gray-50 rounded-lg w-full max-w-[400px] mx-auto" placeholder="<%= t("search") %>">
  </form>
</header>



<%= turbo_stream_from dom_id(@page) %>

<div id="references" class="sm:grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
  <% @page.references.each do |reference| %>
    <%= render "references/item", reference: %>
  <% end %>
</div>

<div class="sm:py-3">
  <div
    class="prose bg-white p-4 sm:p-8 w-full max-w-none animate-fade transition !text-gray-600 rounded-lg shadow border border-gray-50"
    data-controller="jump"
    data-action="mouseup->jump#select touchend->jump#select"
    data-jump-lang-value="<%= @page.language.code %>"
    data-jump-title-value="<%= @page.title %>"
  >
    <div id="body">
      <% if @page.body %>
        <%= render "pages/body", body: @page.body %>
      <% else %>
        <div class="gap-3 flex flex-col">
          <div class="rounded-lg bg-gray-100 h-4 w-full"></div>
          <div class="rounded-lg bg-gray-100 h-4 w-full"></div>
          <div class="flex gap-4">
            <div class="w-2/3 rounded-lg bg-gray-100 h-4"></div>
            <div class="rounded-lg bg-gray-100 h-4 w-1/3"></div>
          </div>
        </div>
      <% end %>
    </div>

    <div
      data-jump-target="menu"
      class="absolute bg-slate-100 p-1 bg-opacity-90 shadow-lg border border-slate-300 rounded animate-fade transition"
      style="visibility: hidden;"
    >
      <a 
        data-jump-target="jump"
        class="block text-sm py-1 px-2 rounded hover:bg-blue-500 hover:text-white no-underline"
      >
        <%= t("jump") %>
      </a>
      <a
        data-jump-target="dig"
        class="block text-sm py-1 px-2 rounded hover:bg-blue-500 hover:text-white no-underline"
      >
        <%= t("dig") %>
      </a>
    </div>
  </div>
</div>

app/views/references/_item.html.erb
<a
  href="<%= reference.url %>"
  class="animate-fade flex flex-col justify-between shadow rounded-lg p-4 text-sm border border-gray-50 mb-3 sm:mb-0 sm:aspect-video transition hover:shadow-lg bg-white"
>
  <div class="line-clamp-3">
    <%= reference.title %>
  </div>
  <div class="text-gray-400 text-xs flex gap-1 items-center">
    <% if reference.image_url.present? %>
      <img class="w-4" src="<%= reference.image_url %>">
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 16 16"><path fill="currentColor" d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0M2.04 4.326c.325 1.329 2.532 2.54 3.717 3.19c.48.263.793.434.743.484q-.121.12-.242.234c-.416.396-.787.749-.758 1.266c.035.634.618.824 1.214 1.017c.577.188 1.168.38 1.286.983c.082.417-.075.988-.22 1.52c-.215.782-.406 1.48.22 1.48c1.5-.5 3.798-3.186 4-5c.138-1.243-2-2-3.5-2.5c-.478-.16-.755.081-.99.284c-.172.15-.322.279-.51.216c-.445-.148-2.5-2-1.5-2.5c.78-.39.952-.171 1.227.182c.078.099.163.208.273.318c.609.304.662-.132.723-.633c.039-.322.081-.671.277-.867c.434-.434 1.265-.791 2.028-1.12c.712-.306 1.365-.587 1.579-.88A7 7 0 1 1 2.04 4.327Z"/></svg>
    <% end %>
    <div class="truncate">
      <%= reference.base_url.match(/https?:\/\/(.+)/)[1] %>
    </div>
  </div>
</a>